apiVersion: v1
kind: Service
metadata:
  name: email-notification-service
spec:
  selector:
    app: email-notification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
